### ISSUE TITLE
Bootstrap Future

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#14]
**Problem**
I was playing with the space in card class. What I figure out is it automatically got `display: flex;` by bootstrap. There are a lot more styles which are given by bootstrap but are not required.
The problem may seem small and can be changed by simply changing our class name. But this may cause a lot of problems in future, especially, if we want to continue this even after the Hackathon. We can't just remember which classes bootstrap already has and design accordingly.

**Solution**
There are 3 possible solutions according to me.

- Use Bootstrap Fully
Currently, we are randomly choosing which part to design ourselves and which to take from bootstrap. Now, we can continue with Bootstrap completely, creating new designs only if they aren't in bootstrap.

- Use Bootstrap Partially
Since bootstrap doesn't have any prefix in its class name, we have to use a prefix. We can modify our code and attach a prefix to all classes to differentiate them from bootstrap.

- Don't Use Bootstrap
We can, of course, remove bootstrap and write our own designs.

Suggestions Needed @shreygupta2809 @gsc2001 @Chief-Blackhood @tichnas

**Comment by tichnas** [comment]
I think since only NavBar needs bootstrap, we can remove it. We can implement navbar using jquery?

**Comment by gsc2001** [comment]
i suggest use complete bootstrap or partially adding your class name
