### ISSUE TITLE
Restrict Background to Homepage only

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#23]
Currently, the background is on the body and will cause background on all pages.

**Comment by shreygupta2809** [comment]
Change the background from body to the header

**Comment by shreygupta2809** [comment]
Dont put header in the other webpages

**Comment by tichnas** [comment]
Have you solved it @shreygupta2809 ? If yes, then plz close this issue and submit a PR.

**Comment by shreygupta2809** [comment]
Yes I have solved it
