### ISSUE TITLE
No Cards on Homepage

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#25]
There are no cards on the homepage. If the backend is still in progress, please include at least 3 cards manually for styling. @shreygupta2809 @gsc2001

**Comment by gsc2001** [comment]
@tichnas  backend is complete .. 
See instructions in pr i made and follow to generate cards

**Comment by gsc2001** [comment]
Got it ?

**Comment by tichnas** [comment]
@gsc2001 Perfect! Sorry, I forgot that...
