### ISSUE TITLE
Can the white background be removed from the bookmark

### ISSUE THREAD

**Issue by gsc2001** [gsc2001/IIIT-GPS#27]
![image](https://user-images.githubusercontent.com/56212978/82665896-5aa16780-9c52-11ea-9d06-f9dd6e0170e0.png)
Can the white background be changed to transparent

**Comment by tichnas** [comment]
Initially, it was transparent but then it was not properly visible. Another option is to add it to the right of the course name (it was like this at start). What do you suggest @gsc2001 ?

**Comment by gsc2001** [comment]
i updated the posittion and size
