### ISSUE TITLE
Displaying Courses

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#3]
For the time being, display elements like <div id=""> </div>, each with unique id, n number of times.
Every three elements should be inside `<div class="row"> </div>`

Like:
```
<div class="row">
<div id=""></div>
<div id=""></div>
<div id=""></div>
</div>
<div class="row">
...
```

**Comment by gsc2001** [comment]
I will start on this using Handlebars.js ... if anyone wants to do with pug please comment as i don't know how to do with pug

**Comment by tichnas** [comment]
> I will start on this using Handlebars.js ... if anyone wants to do with pug please comment as i don't know how to do with pug

Anyone? Sirf Shrey hi h :rofl:
