### ISSUE TITLE
Add courses on Year page

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#36]
Autoload course on the Year page. Currently, I think we only need Year1.
Also, how will we separate courses based on year & semester? Maybe instead of just one number id, we can have 2 or 3 numbers to identify a course. (Like year-sem-courseno or sem-courseno)

**Comment by gsc2001** [comment]
We have that see data.js

**Comment by gsc2001** [comment]
Why need auto load??

**Comment by shreygupta2809** [comment]
I don't think auto load is possible without using node or other server side tools which we are trying to currently avoid

**Comment by gsc2001** [comment]
this is not possible right know therefore i am closing this issue
