### ISSUE TITLE
Add Star Rating

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#37]

**Comment by gsc2001** [comment]
What are you basivally doing ?? 😅😅

**Comment by gsc2001** [comment]
I can't understand

**Comment by tichnas** [comment]
I'm facing trouble in adding Rating.
The procedure to add it is to put `<script {a lot of attributes}></script>` wherever we want it. The problem is that the card is itself formed by a script and there is no way to put a script inside a script.
I'm not very sure if we can run the script using a function because then what will happen to the parameters?
Any solution? @gsc2001 @shreygupta2809 @Chief-Blackhood 
Btw, I'm also asking this on OSDG...
