### ISSUE TITLE
Link Pages & Modify Directory Structure

### ISSUE THREAD

**Issue by gsc2001** [gsc2001/IIIT-GPS#53]
why are there 2 html folder ??

**Comment by tichnas** [comment]
There is a lot to be done about that. I'm modifying the issue.

**Comment by tichnas** [comment]
We should have a proper directory structure for the project. All the html files should be inside `/resources/html/` (except `index.html`).
Please note that all the comments/rating will work only on a server. In the end, we will publish the website on the IIIT server and we need to have `index.html` in the root directory for proper working.

Some points to remember when changing directory structure:

- Change the path to local stylesheets and scripts, including the ones in the vendor folder.

- Change the favicon path.

- Change links (if already inserted).

After modifying the structure, simply add the links.
