### ISSUE TITLE
Course Page: Expanding & Shrinking Functionality

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#57]
The Syllabus & Resources in the Course Page needs expanding and shrinking functionality.

A glimpse of the html structure is:
```
    <section class="expand-shrink shrink">
        <p> _something_ </p>
         <a class="expand-shrink-button">
            _something_
        </a> 
    </section>
```
Implementation:
The class `expand-shrink-button` on click add/remove a class from its immediate parent (`.expand-shrink`) depending on which class it already has.

If possible, try to add a sliding effect using JQuery or something.

**Comment by gsc2001** [comment]
Done in #63
