### ISSUE TITLE
Change tags color

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#62]
The current color (or background color) of the tags make them hard to read in normal size.
Both the color and background color are defined in `.tags li:not(:first-of-type)` in `style.css`
![Screenshot from 2020-05-23 23-14-57](https://user-images.githubusercontent.com/56799401/82737075-c7e4f380-9d4b-11ea-88de-c7d7d2cb80b6.png)

**Comment by Chief-Blackhood** [comment]
I think there is no need to change the color. P.S. Gurkirat and Shrey also agree.
