### ISSUE TITLE
Refine small card size and media queries

### ISSUE THREAD

**Issue by gsc2001** [gsc2001/IIIT-GPS#7]
The small card size is quite large 
![image](https://user-images.githubusercontent.com/56212978/82581229-de554880-9bad-11ea-8f3a-79a47c3885c8.png)
the space in the middle can be reduced

Also the media queries.
Look at this pic
![image](https://user-images.githubusercontent.com/56212978/82672276-c5a46b80-9c5d-11ea-8c84-32065c14edc4.png)

**Comment by tichnas** [comment]
Any more change is needed @gsc2001 ?

**Comment by gsc2001** [comment]
Can you please send a picture
Currently working on bootstrap.. cant fetch till i commit.
To be safe

**Comment by tichnas** [comment]
@gsc2001 Unfortunately, I fetched the latest project and it doesn't include any card to see. I'll create a new issue for this and we will see this later.

**Comment by gsc2001** [comment]
The cards now have become more large
![image](https://user-images.githubusercontent.com/56212978/82666139-d7ccdc80-9c52-11ea-80ec-cb883f93b781.png)

**Comment by gsc2001** [comment]
The text in tags also is wierd

**Comment by gsc2001** [comment]
Please update media queries also
look at this wierd
![image](https://user-images.githubusercontent.com/56212978/82671274-364a8880-9c5c-11ea-93f9-2bbd7ed04fd9.png)

**Comment by gsc2001** [comment]
Even wierder
![image](https://user-images.githubusercontent.com/56212978/82671953-5169c800-9c5d-11ea-91d0-9b7b225e1347.png)
