### ISSUE TITLE
Bug in Latest PR

### ISSUE THREAD

**Issue by tichnas** [gsc2001/IIIT-GPS#70]
In the PR #68 there are some bugs. 

- No courses are shown in my courses even when they are bookmarked.
- From the homepage, no matter which year we click on navbar, we will always go to Year1.

If possible correct these, otherwise don't worry much as we can undo this PR.
(Maybe this is only in my case so please verify)

**Comment by gsc2001** [comment]
its working

**Comment by tichnas** [comment]
Let me check once again properly

**Comment by tichnas** [comment]
@gsc2001 I tried by downloading the latest zip and the bugs are still there. Please check by clearing local storage and/or downloading the zip.

**Comment by tichnas** [comment]
It's strange. Everything is working in Chrome. What can be the problem with my firefox?

**Comment by Chief-Blackhood** [comment]
Bug seems to be on firefox only and it is very strange!!!

**Comment by gsc2001** [comment]
Done
