### ISSUE TITLE
Add css to review form

### ISSUE THREAD

**Issue by gsc2001** [gsc2001/IIIT-GPS#72]
![image](https://user-images.githubusercontent.com/56212978/82752947-5a82a280-9ddf-11ea-9b73-588bef23140a.png)
Need to add CSS

**Comment by tichnas** [comment]
This is rating or review?

**Comment by gsc2001** [comment]
rating

**Comment by tichnas** [comment]
Ohk, I am doing something for this

**Comment by tichnas** [comment]
Should we do this with stars?

**Comment by shreygupta2809** [comment]
Done
